# Generated by Django 5.2.4 on 2025-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Книга в бібліотеці',
                'verbose_name_plural': 'Книги в бібліотеці',
                'ordering': ['author'],
            },
        ),
    ]
