# Generated by Django 5.2.4 on 2025-08-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='termin',
            field=models.PositiveSmallIntegerField(choices=[('3', 3), ('5', 5), ('10', 10), ('15', 15), ('30', 30), ('45', 45), ('60', 60), ('75', 75), ('90', 90)], default='30', max_length=2),
        ),
    ]
