# Generated by Django 5.2.4 on 2025-08-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0003_alter_borrow_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='termin',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 дні'), (5, '5 днів'), (10, '10 днів'), (15, '15 днів'), (30, '30 днів'), (45, '45 днів'), (60, '60 днів'), (75, '75 днів'), (90, '90 днів')], default=30),
        ),
    ]
