# Generated by Django 5.2.4 on 2025-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0004_alter_borrow_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, default='Біографія відсутня', null=True),
        ),
    ]
