# Generated by Django 5.2.4 on 2025-08-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0005_author_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.CharField(blank=True, default='Біографія відсутня', max_length=800, null=True),
        ),
    ]
